### ISSUE TITLE
封面第一行文字左右间距不一致

### ISSUE THREAD

**Issue by ppoffice** [dustincys/PlutoThesis#3]
直接clone自本repo，使用xelatex编译后出现这个问题，使用的tex环境为texlive 2016。
![image](https://cloud.githubusercontent.com/assets/8849362/26628601/492e544c-4631-11e7-9499-1747f086237a.png)

**Comment by dustincys** [comment]
center 这个命令换成 center 环境



Sent from my Mi phoneOn Ruipeng Zhang <notifications@github.com>, May 31, 2017 6:46 PM wrote:直接clone自本repo，使用xelatex编译后出现这个问题，使用的tex环境为texlive 2016。


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dustincys/PlutoThesis","title":"dustincys/PlutoThesis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dustincys/PlutoThesis"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"封面第一行文字左右间距不一致 (#3)"}],"action":{"name":"View Issue","url":"https://github.com/dustincys/PlutoThesis/issues/3"}}}
